#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/idist
#
# IDENTIFICATION
#    src/backend/access/idist/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/idist
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = idistcompare.o idistinsert.o idistpage.o idist.o idistsearch.o \
       idistutils.o idistsort.o idistxlog.o

include $(top_srcdir)/src/backend/common.mk
